### ISSUE TITLE
Newsletter signup needs confirmation

### ISSUE THREAD

**Issue by josephdburdick** [apollostack/apollo#24]
Notify that the email address was accepted/rejected after the user submits email address.

**Comment by helfer** [comment]
Thanks for reporting, we should definitely add that. I will look into it.

**Comment by dominicnguyen** [comment]
- [ ] Clientside email validation
- [ ] Show a notification after closing the overlay

**Comment by dominicnguyen** [comment]
Added a confirmation message for forms: https://github.com/apollostack/apollo/commit/65af55de4095e79096c858c962311f82d6c9a355

Validation is still an issue but not at the heart of this ticket so I'm closing issue.
