### ISSUE TITLE
keyboard focus: website doesn't scroll when pressing spacebar

### ISSUE THREAD

**Issue by debergalis** [apollostack/apollo#25]
Load the page, press spacebar, no scrolling.  Seems to be a keyboard focus issue?  Once you click anywhere on the page scrolling is fine.

**Comment by rajzshkr** [comment]
this issue is due to  overflow-y: scroll; property given in body. If it is removed, it works. Can I give a pull request??

**Comment by stubailo** [comment]
Yes please! It's on `gh-pages` branch!

**Comment by stubailo** [comment]
@rajzshkr any news on that PR?

**Comment by rajzshkr** [comment]
Pease verify and let me know if any help needed. Thanks.

**Comment by helfer** [comment]
Actually, it still doesn't work for me. Can anyone else verify?

**Comment by pawelphilipczyk** [comment]
You're right, it's not.

**Comment by zimt28** [comment]
Works for me. When the page is at the very top the page kinda "shakes" first, but then it works fine. If the page is already scrolled down, I don't have any issues.

**Comment by dominicnguyen** [comment]
Thanks for the assist @pawelphilipczyk and @rajzshkr. Position changes ended up affecting the scroll position of the overlay so had to tackle it via JS. Got to the bottom of it [here](https://github.com/apollostack/apollo/commit/cae372e34d325a4da7a5d10e8385669e4ae63db2).

**Comment by stubailo** [comment]
Awesome, works!
