### ISSUE TITLE
resolvers management

### ISSUE THREAD

**Issue by abhiaiyer91** [apollostack/apollo#29]
I was wondering if you guys were thinking about how resolvers will be managed as the Namespaces grow in number and in size? 

I was thinking you could do something like...

```js

function generateRootQuery(Query) {
 return {
    Query
  };
}

function author(root, args){
      return Authors.findOne({
        firstName: args.firstName,
        lastName: args.lastName
      }, {
        fields: {
          'firstName': 1,
          'lastName': 1
        }
      });
    }
}

export const rootQuery = generateRootQuery({ author });
```
This would work well becuse you could then separate the query resolvers into modules, then do a rootQuery export. 

Then you could combine resolvers as well

```js
function rootResolver(Query, Types) {
   return Object.assign({}, {Query}, {...Types});
}


// used like

import rootQuery from '/imports/data/rootQuery';
import Author from '/imports/data/resolvers/Author';

export default rootResolver(rootQuery, {Author});
```

I dont know something like that?

**Comment by helfer** [comment]
Composing resolve functions is a great idea! Sashko and I have been toying with the idea a little bit, but I haven't implemented anything for it.

Composing resolvers in the way you propose is actually already possible right now, so I think it would just be a matter of making an 'official' recommendation of how people should do it.

Just one question: I don't really see any namespacing in your examples. Maybe we could add that with a simple function where you can give both the field and the resolve function a prefix or something?

Ideally, we'd like to be able to compose both type definitions and resolve functions, such that every type would be 'portable' and could be plugged into any schema.

**Comment by abhiaiyer91** [comment]
Could I see a sketch of this?

> Ideally, we'd like to be able to compose both type definitions and resolve functions, such that every type would be 'portable' and could be plugged into any schema.

**Comment by abhiaiyer91** [comment]
Yes the above could already be done today and could be just shipped as utilities.

**Comment by stubailo** [comment]
Should we move this to https://github.com/apollostack/graphql-tools? Seems more relevant to the server component!

**Comment by abhiaiyer91** [comment]
yes def!
