### ISSUE TITLE
Using express in meteor deployments, is it secure?

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/apollo#37]
Hi, for Meteor applications you are using a standalone express server that is ruinning on port 4000. How secure is this to deploy to the live app? What if the app crashes? I have several deployments on Galaxy, thinking of using GraphQl, but that express server scares me a bit. Will it be detected by Meteor app and crash as well? This way Galaxy would start a new instance with no issues. Thanks for any advice.

**Comment by tomitrescak** [comment]
I guess, my question is, can apollo server run in-proc with meteor appllication in order to assure the stability of the application? My naive way of doing that was:

```
WebApp.connectHandlers.use("/graphql", apolloServer(async () => {
    return {
      graphiql: true,
      pretty: true,
      schema,
      resolvers
    };
}));
```

Which of course does not work ... but something in this ballpark would be great!

**Comment by stubailo** [comment]
Asking the Galaxy team about it!

**Comment by tomitrescak** [comment]
@stubailo did you have any response from the galaxy team? I think I got enough knowledge to start bringing this into production. In combination with redux it's pure awesomeness. But the stability is priority num. 1 for now. Thanks.

**Comment by stubailo** [comment]
Oh yeah - I checked up with then and only one port is externally accessible. So there shouldn't be any security concerns with running a different port as an implementation detail.

**Comment by tomitrescak** [comment]
Great, thanks.
