### ISSUE TITLE
merging schemas

### ISSUE THREAD

**Issue by payner35** [apollostack/apollo#39]
can i split my schema into more than one file.. and then import.  something like...

eventSchema.js
```
const eventSchema = `
    type Event {
      _id: String
      title: String
      subtitle: String
      description: String
      region: String
    }
    
    type QueryEvent {
      allEvents: [Event]  
      event(id: String, title: String): Event
  
    }
    schema {
      query: QueryEvent
    }
`;

export default () => [eventSchema];
```

index.js
```
import eventSchema from './eventSchema';

export default {
    eventSchema
};
```

**Comment by stubailo** [comment]
The approach I’ve taken so far is have parts of my schema/resolvers in different modules, and import them all from my server:

- Small module that defines just a few types and resolvers: https://github.com/apollostack/GitHunt/blob/8e8f01dd341d279cb26aada078230d05a4de34f5/api/sql/schema.js
- Import from another module, merge, and re-export: https://github.com/apollostack/GitHunt/blob/8e8f01dd341d279cb26aada078230d05a4de34f5/api/schema.js#L77-L78
- Then use them in the apollo server constructor: https://github.com/apollostack/GitHunt/blob/8e8f01dd341d279cb26aada078230d05a4de34f5/index.js#L16-L17

**Comment by payner35** [comment]
Ok thanks..

Here what seems to work for me so far...

schema.js
```
import { Events } from '/imports/lib/collections';

export const schema = [`
    type Event {
      _id: String
      title: String
      subtitle: String
      description: String
      region: String
    }
    
    type QueryEvent {
      allEvents: [Event]  
      event(id: String, title: String): Event
  
    }
    schema {
      query: QueryEvent
    }
`];



export const resolvers = {
    QueryEvent: {
        allEvents(root, args) {
            return Events.find().fetch();
        },
        event(root, args) {
            return Events.find().fetch();
        }
    }
};

```

idex.js
```
import { merge } from 'lodash';

import { schema as eventSchema, resolvers as eventResolver } from './eventSchema';

export const resolvers = merge(eventResolver);
export const schema = [...eventSchema];
```


and then
```
import express from 'express';
import { apolloServer } from 'graphql-tools';
import { schema } from '../data';
import { resolvers } from '../data';


export default function () {

    const GRAPHQL_PORT = 8080;

    const graphQLServer = express();

    graphQLServer.use('/graphql', apolloServer({
        graphiql: true,
        pretty: true,
        schema,
        resolvers
        //mocks: Mocks,
    }));

    graphQLServer.listen(GRAPHQL_PORT, () => console.log(
        `GraphQL Server is now running on http://localhost:${GRAPHQL_PORT}/graphql`
    ));
}

```



in my index.js...   why is it  [...eventSchema]. ?   the 3 dots means I am creating a new version of the schema on start up?

**Comment by stubailo** [comment]
@payner35 the `schema` argument to `apolloServer` accepts an array of strings. So since `eventSchema` is an array of strings, let's say you had something else like `commentSchema` or whatever, then you would need to merge the two arrays like:

```js
[...eventSchema, ...commentSchema]
```

Think of it like `merge` for arrays - it's unnecessary if you just have one item, of course.
