### ISSUE TITLE
"Join the newsletter" not working on apollostack.com

### ISSUE THREAD

**Issue by kachkaev** [apollostack/apollo#52]
Steps to reproduce:

1. Open apollostack.com
2. Click Sign up for email updates
3. Enter a valid email address
4. Open developer tools
5. Press SIGN UP
6. 
```
ReferenceError: event is not defined
<anonymous>
 main.js:18
n.event.dispatch()
 jquery.min.js:3
n.event.add/r.handle()
 jquery.min.js:3
```

FF 46.0.1 on Ubuntu

**Comment by kachkaev** [comment]
Just upgraded FF to 47.0 – the issue remains.

**Comment by GrandathePanda** [comment]
Can confirm  and also problem seems exclusive to FF, works on chrome.

**Comment by cfnelson** [comment]
Confirmed on FF 47.0.1

```js
ReferenceError: event is not defined
<anonymous>
 main.js:28
n.event.dispatch()
 jquery.min.js:3
n.event.add/r.handle()
 jquery.min.js:3
```

Code snippet below where the error is being raised.

```js 
$('#newsletter-form').submit(function(e) {
    e.preventDefault()
    var email = event.target.email.value; // - The error being raised. 
    var latestformsubmit = 'Apollo Newsletter Subscription'
    analytics.identify(email, {email: email, LatestFormSubmit: latestformsubmit});
    analytics.track('web.apollo-newsletter');
    $('.newsletter-form').addClass('confirmed');

    setTimeout(function(){
      $('.layout').attr('class', 'layout');
    }, 1200);
  })
```

Signup works on chrome.

**Comment by lorensr** [comment]
Thanks everyone, looks like fix is just changing `event -> e`. Funny that this actually works in Chrome 😜 

@stubailo is the site open-source? I'm not seeing it under `apollostack/*`

**Comment by stubailo** [comment]
@lorensr the site is under `gh-pages` on this very repository!

**Comment by lorensr** [comment]
😆 haha, thank you

Thank you @kachkaev @GrandathePanda @cfnelson for reporting and confirming 🙌😃 I downloaded FF, and now it's working for me. Now to get away from this crazy font and catch this wild Krabby! 💃
