### ISSUE TITLE
Schema error

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/apollo#54]
Dear, I am receiving a weird schema error on following schema:

```
type NotificationParameter {
    scheduleName: String,
    practicalName: String,
    exerciseName: String,
    rank: Int,
    count: Int,
    mark: Float
  }

  type Notification {
    _id: String,
    userId: String,
    code: String,
    date: String,
    parameters: [NotificationParameter]
  }

  type RootQuery {
    notifications: [Notification]
  }

  schema {
    query: RootQuery
  }
```

I'm getting: `Resolve function missing for \"Notification.parameters\"`

When I use a simple String type in:

```
  type Notification {
    parameters: [String]
  }
```

the error disappears.

**Comment by helfer** [comment]
This error message is the expected behavior.

The schema generator in Apollo Server expects a definition of a resolve function for any fields of non-scalar types (String is a scalar type, thus no resolve function is required).

**Comment by tomitrescak** [comment]
Thanks @helfer ... noob here .. thought that it is done automatically.
