### ISSUE TITLE
Intro email to people who star?

### ISSUE THREAD

**Issue by lorensr** [apollostack/apollo#58]
Eg this one I got a few hours after starring Onsen UI:

![image](https://cloud.githubusercontent.com/assets/251288/16791358/3784c062-488c-11e6-9020-7a31d71d6fc5.png)

**Comment by lorensr** [comment]
maybe for meteor too @theadactyl

**Comment by stubailo** [comment]
Pretty cool idea!

**Comment by danahmadi** [comment]
This is complete!
