### ISSUE TITLE
Question : Ability to use an API to get Data

### ISSUE THREAD

**Issue by rwatts3** [apollostack/apollo#61]
Greetings, 

I am just starting out with Apollostack and I have a generic question regarding data and api calls.
Would it be possible to somehow get analytics data using google analytics api ? 
If this is already answered or there is already documentation could you please point me in the right direction. 

Thank you.

**Comment by helfer** [comment]
Hi @rwatts3, I don't really understand what you're asking. Can you give a concrete example of what you're trying to do?

Also, you might have more luck asking on the repo specific to your question (apollo-client, presumably).

**Comment by rwatts3** [comment]
Hi @helfer I'm trying to see if Apollo not sure Client or Server can be used to retrieve data from a REST service such as google analytics api.

**Comment by helfer** [comment]
@rwatts3 Okay, I see. In that case the answer is yes, you can do that on the server. You may find this medium post that I wrote a while ago instructive, in particular the part about the fortuneCookie API: https://medium.com/apollo-stack/tutorial-building-a-graphql-server-cddaa023c035

**Comment by rwatts3** [comment]
Awesome that's exactly what i'm looking for thank you !
