### ISSUE TITLE
TEST - Comments via GitHub's GraphQL API

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo#66]
This is an issue thread just to test commenting via GitHub's GraphQL API. Try to post a comment or add a reaction to an existing comment!

**Comment by helfer** [comment]
Testing a first comment, with emoji :tada:

**Comment by agauniyal** [comment]
ア Okay ア

**Comment by batjko** [comment]
How do I get at the subjectId of this comment? 66 won't work.

**Comment by batjko** [comment]
Go GraphQL... **pants: shat**

**Comment by batjko** [comment]
Ha, worked! 
I had to query for issues first and track down the id of the latest one, not at all obvious.
I'm sure there's a better way, but the documentation isn't clear to me.

**Comment by Ruzo** [comment]
My mutated comment test :)

**Comment by dzello** [comment]
Hello from GraphiQL!

**Comment by dallonf** [comment]
@dzello [Now post a comment that contains the mutation that posted it](https://en.wikipedia.org/wiki/Quine_(computing))

**Comment by homaxweb** [comment]
It's awesome

**Comment by tekhaus** [comment]
GraphQL - Test Comment

**Comment by JosieGittingTheHub** [comment]
Hi everybody, have a great day! :spock-hand:

**Comment by Zombiehelp54** [comment]
Hello from GraphiQL!

**Comment by Zombiehelp54** [comment]
1

**Comment by comradewarlock** [comment]
Hello from GraphiQL!

**Comment by comradewarlock** [comment]
<body onload=alert('test1')>

**Comment by comradewarlock** [comment]
<b onmouseover=alert('Wufff!')>click me!</b>

**Comment by comradewarlock** [comment]
'<script><b onmouseover=alert('Wufff!')>click me!</b></script>'

**Comment by comradewarlock** [comment]
<body onload=alert('test1')>

**Comment by comradewarlock** [comment]
console.warn('alert is deprecated.')

**Comment by comradewarlock** [comment]
><script>console.warn('alert is deprecated.')</script>

**Comment by fkarakas** [comment]
Hello from GraphiQL!

**Comment by fkarakas** [comment]
Hello from GraphiQL!

**Comment by fkarakas** [comment]
Hello from GraphiQL!

**Comment by fkarakas** [comment]
Hello from GraphiQL!

**Comment by fkarakas** [comment]
Hello from GraphiQL!

**Comment by fkarakas** [comment]
Hello from GraphiQL!

**Comment by fkarakas** [comment]
Hello from GraphiQL!

**Comment by Bowen8888** [comment]
Hello from GraphiQL!

**Comment by IkramKhanNiazi** [comment]
BODY_CONTENT

**Comment by akashsateesh** [comment]
Hello from GraphiQL!

**Comment by akashsateesh** [comment]
Hello from GraphiQL!

**Comment by chrisrowe** [comment]
<3

**Comment by chrisrowe** [comment]
It works!

**Comment by aniljacob** [comment]
Hello from GraphiQL!

**Comment by kuzmaMinin** [comment]
Hello from GraphiQL!

**Comment by kuzmaMinin** [comment]
Hello from GraphiQL от Васи!

**Comment by kuzmaMinin** [comment]
Ну вы блин даете

**Comment by kuzmaMinin** [comment]
fdddd

**Comment by hackrzvijay** [comment]
Hello

**Comment by LongJakeparker** [comment]
Hello GraphQL

**Comment by LongJakeparker** [comment]
Hello from GraphQL!!!

**Comment by LongJakeparker** [comment]
Hello from GraphQL!!!
